!classDefinition: #AlanKay category: #'Ejercicio 7'!
DenotativeObject subclass: #AlanKay
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 7'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'AlanKay class' category: #'Ejercicio 7'!
AlanKay class
	instanceVariableNames: ''!

!AlanKay class methodsFor: 'as yet unclassified' stamp: 'JR 3/31/2019 15:55:46'!
dateOfBirth
	^ June/23/1912! !


!classDefinition: #Alanturing category: #'Ejercicio 7'!
DenotativeObject subclass: #Alanturing
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 7'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Alanturing class' category: #'Ejercicio 7'!
Alanturing class
	instanceVariableNames: ''!

!Alanturing class methodsFor: 'as yet unclassified' stamp: 'JR 3/31/2019 15:56:40'!
dateOfBirth
	^June/23/1912! !


!classDefinition: #AlonsoChurch category: #'Ejercicio 7'!
DenotativeObject subclass: #AlonsoChurch
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 7'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'AlonsoChurch class' category: #'Ejercicio 7'!
AlonsoChurch class
	instanceVariableNames: ''!

!AlonsoChurch class methodsFor: 'as yet unclassified' stamp: 'JR 3/31/2019 15:59:07'!
ageDifferenceWith: aPerson
	^ self dateOfBirth distanceTo: aPerson dateOfBirth .! !

!AlonsoChurch class methodsFor: 'as yet unclassified' stamp: 'JR 3/31/2019 15:58:05'!
ageDifferenceWithAlanTuring
	^ self dateOfBirth distanceTo: Alanturing dateOfBirth .! !

!AlonsoChurch class methodsFor: 'as yet unclassified' stamp: 'JR 3/31/2019 15:56:05'!
dateOfBirth
	^June/14/1903! !


!classDefinition: #DanIngalls category: #'Ejercicio 7'!
DenotativeObject subclass: #DanIngalls
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 7'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'DanIngalls class' category: #'Ejercicio 7'!
DanIngalls class
	instanceVariableNames: ''!

!DanIngalls class methodsFor: 'as yet unclassified' stamp: 'JR 3/31/2019 15:57:09'!
dateOfBirth
	^June/1/1944! !
