!classDefinition: #AlanTuring category: #'Ejercicio 6'!
DenotativeObject subclass: #AlanTuring
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 6'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'AlanTuring class' category: #'Ejercicio 6'!
AlanTuring class
	instanceVariableNames: ''!

!AlanTuring class methodsFor: 'as yet unclassified' stamp: 'JR 3/31/2019 15:35:06'!
doesNotUnderstand: aMessage
	^ 'No entiendo lo que me decis con ', aMessage name.! !
